# Generated by Django 4.2.3 on 2023-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=4)),
                ('fiddler', models.CharField(max_length=100)),
                ('tuning', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
