# Generated by Django 4.2.3 on 2023-07-13 13:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tunes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tune',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='fiddler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='key',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('D', 'D'), ('G', 'G'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tune',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tune',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tuning',
            field=models.CharField(default='GDAE', max_length=4),
        ),
    ]
