# Generated by Django 4.2.3 on 2023-07-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tune', '0002_tune_user_alter_tune_description_alter_tune_fiddler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tunes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
