# Generated by Django 4.2.3 on 2023-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune', '0003_alter_tune_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
