# Generated by Django 4.2.3 on 2023-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune', '0004_alter_tune_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
