# Generated by Django 4.2.3 on 2023-07-16 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tune', '0005_alter_tune_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tune',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
